micronaut:
  application:
    name: subscriptionMicroservice
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://${DB_HOST:db}/${DB_NAME:subscription}
    username: ${DB_USER:todo}
    password: ${DB_PASSWORD:todosecret}
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.subscription.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
kafka:
  bootstrap:
     servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`}
netty:
  default:
    allocator:
      max-order: 3